name: Build
on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  windows_build:
    runs-on: windows-2019   
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: my_repo_path
      - name: Checkout fmt
        uses: actions/checkout@v2
        with:
          repository: fmtlib/fmt
          path: fmt_repo_path
      - name: Setup Visual C++ environment
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
      - name: Build fmt
        run: |
          SET "INSTALL_ROOT=%~d0\usr\local"
          ECHO INSTALL_ROOT = %INSTALL_ROOT%
          cmake -S fmt_repo_path -B fmt_repo_path\build -DCMAKE_INSTALL_PREFIX="%INSTALL_ROOT%" -DFMT_TEST:BOOL=OFF
          cmake --build fmt_repo_path\build --config Debug
          cmake --install fmt_repo_path\build --config Debug
        shell: cmd
#      - name: Cache proj1 build
#        id: proj1-build
#        uses: actions/cache@v3
#        with:
#          path: my_repo_path\proj1\build
#          key: ${{ runner.os }}-proj1-build
      - name: Build proj1
#        if: steps.proj1-build.outputs.cache-hit != 'true'
        run: |
          cmake -S my_repo_path\proj1 -B my_repo_path\proj1\build
          cmake --build my_repo_path\proj1\build --config Debug
        shell: cmd
      - name: Build proj2
        run: |
          cmake -S my_repo_path\proj2 -B my_repo_path\proj2\build -DCMAKE_PREFIX_PATH:PATH="%INSTALL_ROOT%"
          cmake --build my_repo_path\proj2\build --config Debug
        shell: cmd
